# .pre-commit-config.yaml
# Path: .pre-commit-config.yaml
#
# Purpose:
# - Configure pre-commit hooks to run locally before commits (formatting, linting,
#   basic repo checks). This helps keep the codebase consistent and prevents
#   obvious mistakes from reaching CI.
#
# Notes:
# - Rev values use stable/latest tags where appropriate; pin to exact versions
#   if your project policy requires strict reproducibility.
# - Install locally with: pip install pre-commit && pre-commit install
# - Run all hooks against all files with: pre-commit run --all-files

repos:
  # General pre-commit repository of useful small hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # update as desired
    hooks:
      - id: check-yaml            # ensure YAML files are valid
      - id: end-of-file-fixer    # ensure files end with newline
      - id: trailing-whitespace  # remove trailing whitespace
      - id: check-added-large-files

  # Black: code formatter for Python
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        args: ["--line-length=88"]

  # isort: sort imports deterministically
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  # Ruff: fast linter (combines flake8-like checks + autofix)
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: stable
    hooks:
      - id: ruff
        args: ["--fix"]   # remove `--fix` if you prefer only diagnostics

  # Optionally: check for secrets (commented out by default)
  # - repo: https://github.com/Yelp/detect-secrets
  #   rev: v1.0.3
  #   hooks:
  #     - id: detect-secrets
  #       args: ["--baseline", ".secrets.baseline"]
